name: Publish Svelte Package

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    name: Build, test, and release
    runs-on: ubuntu-latest

    permissions:
      contents: read      # for checkout
      packages: write     # for npm publish

    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js & authenticate to GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version-file: ./.nvmrc
          registry-url: 'https://npm.pkg.github.com'
          scope: '@KingBain'
          always-auth: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build TypeScript
        run: npm run build

      - name: Publish to GitHub Packages
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
