jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ steps.create_token.outputs.token }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 14
      - name: Cache node modules
        uses: actions/cache@v4.2.3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        env:
          NPM_TOKEN: ${{ steps.create_token.outputs.token }} 
        run: npm ci
      - name: Build TypeScript
        run: npm run build
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}
          NPM_TOKEN: ${{ steps.create_token.outputs.token }}
          GIT_AUTHOR_NAME: "Koj Bot"
          GIT_AUTHOR_EMAIL: "bot@koj.co"
          GIT_COMMITTER_NAME: "Koj Bot"
          GIT_COMMITTER_EMAIL: "bot@koj.co"
